version: "3.9"
services:
  db:
    image: postgres:16
    container_name: chatkick-postgres
    environment:
      POSTGRES_DB: chatkick
      POSTGRES_USER: chatkick
      POSTGRES_PASSWORD: chatkick
    ports:
      - "5432:5432"
    volumes:
      - chatkick_pg:/var/lib/postgresql/data
volumes:
  chatkick_pg:
