services:
  - type: web
    name: chatkick-web
    env: node
    rootDir: backend
    buildCommand: npm install && npm run build:all && npx prisma db push
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: chatkick-db
          property: connectionString
      # SMTP (اختياري)
      - key: SMTP_HOST
        value: ""
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        value: ""
      - key: SMTP_PASS
        value: ""
      - key: SMTP_FROM
        value: "ChatKick <no-reply@chatkick.local>"

databases:
  - name: chatkick-db
    databaseName: chatkick
    user: chatkick
